#!/bin/sh

studio_formatter="$ANDROID_STUDIO/bin/format.sh"
STUDIO_PROPERTIES="$(cd "$(dirname "$0")"; pwd -P)/idea.properties"
export STUDIO_PROPERTIES
"$studio_formatter" "$1" || {
  echo 'fatal: `format` failed for:' "$1" >&2
  exit 1
}
