#!/bin/sh

if [[ -z "${ANDROID_STUDIO}" ]] || [ ! -d "${ANDROID_STUDIO}" ]; then
  echo "ANDROID_STUDIO is undefined or contains path which doesn't not exist."
fi

if [ "$(uname)" == "Darwin" ]; then
  studio_formatter="$ANDROID_STUDIO/Contents/bin/format.sh"
else
  studio_formatter="$ANDROID_STUDIO/bin/format.sh"
fi
STUDIO_PROPERTIES="$(cd "$(dirname "$0")"; pwd -P)/idea.properties"
export STUDIO_PROPERTIES
tr '\n' ' ' <&0 | xargs "$studio_formatter" || {
  echo 'fatal: `format` failed' >&2
  exit 1
}
