#!/bin/sh

if [ "$(uname)" == "Darwin" ]; then
  studio_formatter="$ANDROID_STUDIO/Contents/bin/format.sh"
else
  studio_formatter="$ANDROID_STUDIO/bin/format.sh"
fi
STUDIO_PROPERTIES="$(cd "$(dirname "$0")"; pwd -P)/idea.properties"
export STUDIO_PROPERTIES
xargs "$studio_formatter" "$1" <&0 || {
  echo 'fatal: `format` failed for:' "$1" >&2
  exit 1
}
