#!/bin/sh

if [[ -z "${ANDROID_STUDIO}" ]] || [ ! -d "${ANDROID_STUDIO}" ]; then
  echo "ANDROID_STUDIO is undefined or contains path which doesn't not exist."
fi

if [ "$(uname)" == "Darwin" ]; then
  studio_linter="$ANDROID_STUDIO/Contents/bin/inspect.sh"
else
  studio_linter="$ANDROID_STUDIO/bin/inspect.sh"
fi
STUDIO_PROPERTIES="$(cd "$(dirname "$0")"; pwd -P)/idea.properties"
export STUDIO_PROPERTIES

lint_xml="$(cd "$(dirname "$0")"; pwd -P)/Project_Default.xml"

"$studio_linter" "$1" "$lint_xml" "$2" || {
  echo 'fatal: `lint` failed' >&2
  exit 1
}

