#!/bin/bash

root="$(git rev-parse --show-toplevel)"
[ -d "$root" ] || exit 1

owndir="$(cd "$(dirname "$0")"; pwd -P)"

OS_NAME=$(uname)

if [ "$OS_NAME" = "Darwin" ]; then
  FIND_ARGS="-perm +0111"
else
  FIND_ARGS="-executable"
fi
tmp_file="$root/.git/tmp-filelist.txt"
echo "Processing formatter script ..."
git diff --name-only --cached --diff-filter=ACM | awk -v prefix="$root/" '{print prefix $0}' > "$tmp_file"
"$owndir/formatter" < "$tmp_file" || abort=1
cat tmp-filelist.txt | xargs git add
[ $abort -eq 0 ] || exit 1

echo "Processing linter script ..."
# [ -d "$root/build/linter" ] && rm -rf "$root/build/linter"
# "$owndir/linter" "$root" "$root/build/linter" || exit 1
"python" "$owndir/android-linter.py" "$root" < "$tmp_file" || exit 1
# echo "Lint result can be found in PROJECT/build/linter"
rm "$tmp_file"